services:
  - type: web
    name: uthm-scr
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: uthm-db
          property: connectionString

databases:
  - name: uthm-db
    plan: free
